spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/session
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration
  docker:
    compose:
      lifecycle-management: start_only